#!/usr/bin/env bun
/**
 * Codegen for embedding the Vite build into the compiled `tasks` binary
 * (issue #25 / ADR-0016). Run AFTER `vite build`, BEFORE `bun build --compile`.
 *
 * Why codegen: Bun embeds a file only when it is imported with
 * `with { type: "file" }` (a positional `.js`/`.css` arg is treated as a JS
 * entrypoint to bundle, NOT embedded verbatim — confirmed empirically). Vite's
 * output filenames are content-hashed and unknown ahead of time, so we scan
 * `web/dist` and emit one static import per built file plus a route→`$bunfs`
 * manifest. The generated module is read by src/serve/assets.ts at runtime.
 *
 * The generated file (src/serve/web-assets.generated.ts) is gitignored: it is a
 * build artifact derived from web/dist. When absent (dev / `bun run src/cli.ts`)
 * the dynamic import in assets.ts fails closed and `serve` runs API-only.
 */
import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const REPO_ROOT = join(import.meta.dir, "..");
const DIST = join(REPO_ROOT, "web", "dist");
const OUT = join(REPO_ROOT, "src", "serve", "web-assets.generated.ts");

if (!existsSync(join(DIST, "index.html"))) {
  console.error(`gen-web-assets: ${DIST}/index.html not found — run \`vite build\` first.`);
  process.exit(1);
}

// Import paths are relative to the generated module's location (src/serve/).
const fromGen = (abs: string) => {
  const rel = relative(join(REPO_ROOT, "src", "serve"), abs);
  return rel.startsWith(".") ? rel : `./${rel}`;
};

interface Entry {
  varName: string;
  importPath: string;
  route: string; // request path the server serves it under
}

const entries: Entry[] = [];
let id = 0;

// index.html
entries.push({
  varName: `a${id++}`,
  importPath: fromGen(join(DIST, "index.html")),
  route: "/index.html",
});

// hashed assets under web/dist/assets
const assetsDir = join(DIST, "assets");
if (existsSync(assetsDir)) {
  for (const name of readdirSync(assetsDir)) {
    entries.push({
      varName: `a${id++}`,
      importPath: fromGen(join(assetsDir, name)),
      route: `/assets/${name}`,
    });
  }
}

const importLines = entries
  .map((e) => `import ${e.varName} from "${e.importPath}" with { type: "file" };`)
  .join("\n");

const indexEntry = entries.find((e) => e.route === "/index.html")!;
const assetEntries = entries.filter((e) => e.route !== "/index.html");

const assetPairs = assetEntries.map((e) => `  ${JSON.stringify(e.route)}: ${e.varName},`).join("\n");

const out = `// @ts-nocheck
// GENERATED by scripts/gen-web-assets.ts — do not edit, do not commit.
// Embeds the Vite build (web/dist) into the compiled binary. See src/serve/assets.ts.
// @ts-nocheck above: the \`with { type: "file" }\` imports resolve to raw build
// artifacts (.js/.css/.html) that have no TS declarations; Bun's bundler reads
// them as embedded files at compile time. tsc would otherwise flag them.
${importLines}

/** \`$bunfs\` path of the embedded index.html (SPA shell). */
export const indexHtmlPath: string = ${indexEntry.varName};

/** route ("/assets/index-XXX.js") -> embedded \`$bunfs\` path. */
export const assetPaths: Record<string, string> = {
${assetPairs}
};
`;

writeFileSync(OUT, out, "utf-8");
console.log(`gen-web-assets: wrote ${OUT} (${entries.length} embedded files)`);
